action_magnitude_reward_scale: 0.75
action_scale: 1
agent_hidden_size: 512
amp_components_path: null
anneal_lr: false
args_file: scripts/smooth_policy/amp_history/configs/rma/amp_default.yaml
batch_size: 32768
clip_coef: 0.2
clip_vloss: false
config: scripts/smooth_policy/amp_history/configs/new_juggle/pid_noise_config.yaml
demo_data_path: scripts/smooth_policy/amp_history/amp_training/amp_data/dataset_with_action_history_larger.pt
device: cuda:0
disc_batch_size: 256
disc_debug_interval: 5000
disc_grad_penalty: 5.0
disc_hidden_sizes:
- 128
- 128
disc_learning_rate: 1.0e-05
disc_logit_reg: 0.01
disc_replay_buffer_size: 100000
disc_replay_samples: 4096
disc_reward_weight: 0.5
disc_weight_decay: 0.0001
discriminator_path: null
edge_eval_episodes: 5
edge_eval_interval: 10
encoder_path: null
ent_coef: 0.01
env_encoder_hidden_size:
- 128
- 128
env_latent_dim: 12
env_spec_pool_path: null
env_var_dim: 8
gae_lambda: 0.95
gamma: 0.99
latent_noise_std: 0.05
learning_rate: 0.0001
log_parent_dir: runs/rma/larger_test/run
max_grad_norm: 0.5
minibatch_size: 256
model_path: null
model_save_interval: 50
norm_adv: true
num_discriminator_updates: 3
num_envs: 64
num_iterations: 10000
num_randomized_envs_total: 500
num_steps: 512
run_name: rma_default
seed: 0
target_kl: null
task_reward_weight: 0.5
temporal_alignment_horizon: 4
temporal_alignment_reward_scale: 0.75
update_epochs: 5
use_action_discriminator: false
use_last_action_in_policy_state: true
use_on_demand_env_sampling: true
vf_coef: 0.5
