"""Self-contained tests for the paddle sysid module.

A synthetic session is generated *with the Box2D plant itself* under known gains and written in
the recording layout, so the replay must reproduce it exactly with the true gains and the
CMA-ES fit must move towards them from a wrong start. Runs in well under a minute, no robot
data needed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import h5py
import numpy as np
import pytest

_REPO = Path(__file__).resolve().parents[4]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from sysid.paddle_pid.code.dataset import load_session, split_train_val, session_attrs, parse_trial_name  # noqa: E402
from sysid.paddle_pid.code.replay import (PaddleReplayer, PlantParams, build_replay_sim_config, evaluate_trials,  # noqa: E402
                                         load_base_config)
from sysid.paddle_pid.code.cmaes_fit import GainBounds, CandidateEvaluator, run_cmaes  # noqa: E402

TRUE = PlantParams(kp=6000.0, ki=200.0, kd=120.0, paddle_density=3000.0)
ATTRS = {"hist_len": 1, "move_lims": [0.26, 0.12], "workspace_lims": [-0.83, -0.42, -0.35, 0.39],
         "edge_lims": [0.8, 0.1, -0.188, -0.22]}
CONDITIONS = {"xpos_delta0.50": ([-0.80, 0.0], [0.5, 0.0]), "yneg_delta0.66": ([-0.65, 0.30], [0.0, -0.66]),
              "diagpos_delta0.33": ([-0.55, -0.30], [-0.33, 0.33])}


def _write_trial(path, name, pose, speed, desired, actions, settle):
    n = pose.shape[0]
    tv = np.zeros((n, 35))
    tv[:, 0] = 1.7e9 + 0.05 * np.arange(n)
    tv[:, 5:7], tv[:, 11:13], tv[:, 26:28] = pose, speed, desired
    tv[:, 32], tv[:, 34] = -0.8, 1.0
    with h5py.File(path, "w") as f:
        f.create_dataset("train_vals", data=tv)
        f.create_dataset("actions", data=actions.astype(np.float32))
        f.create_dataset("is_settle_step", data=settle.astype(np.int8))
        f.attrs["trial_name"] = name
        for k, v in ATTRS.items():
            f.attrs[k] = v
        f.attrs["trial_type"] = "line"


@pytest.fixture(scope="module")
def session(tmp_path_factory):
    """3 conditions × 3 repeats generated by the sim under TRUE gains (tiny start jitter per repeat)."""
    d = tmp_path_factory.mktemp("paddle_session")
    sim_cfg = build_replay_sim_config(load_base_config(), ATTRS)
    rep = PaddleReplayer(sim_cfg)
    rep.set_params(TRUE)
    rng = np.random.RandomState(0)
    idx = 0
    manifest = {"trials": []}
    for cond, (start, act) in CONDITIONS.items():
        for repeat in (1, 2, 3):
            n_settle, n_act = 3, 14
            n = n_settle + n_act
            actions = np.vstack([np.zeros((n_settle, 2)), np.tile(act, (n_act, 1))])
            settle = np.arange(n) < n_settle
            p0 = np.asarray(start) + rng.uniform(-0.003, 0.003, 2)
            rep.reset_to(p0, np.zeros(2))
            pose = np.zeros((n, 2)); speed = np.zeros((n, 2)); desired = np.zeros((n, 2))
            pose[0] = rep._paddle_pose_robot()
            for k in range(n):
                desired[k] = rep.target_from(pose[k], actions[k])
                if k + 1 < n:
                    rep.env.step(actions[k]); rep._park_puck()
                    pose[k + 1] = rep._paddle_pose_robot()
                    speed[k + 1] = (pose[k + 1] - pose[k]) / rep.dt
            name = f"traj_{idx:03d}_{cond}_trial{repeat}"
            _write_trial(d / f"{name}.hdf5", name, pose, speed, desired, actions, settle)
            manifest["trials"].append({"trial_name": name, "protective_stop": False, "aborted_at_step": None})
            idx += 1
    with open(d / "manifest.json", "w") as fh:
        json.dump(manifest, fh)
    return d


def test_parse_trial_name():
    assert parse_trial_name("traj_054_arc_wide_v0.22_trial1") == (54, "arc_wide_v0.22", 1)
    with pytest.raises(ValueError):
        parse_trial_name("nope")


def test_load_and_split(session):
    trials = load_session(session)
    assert len(trials) == 9 and [t.index for t in trials] == list(range(9))
    assert trials[0].n_steps == 17 and trials[0].settle[:3].all() and not trials[0].settle[3:].any()
    attrs = session_attrs(trials)
    assert attrs["hist_len"] == 1 and attrs["move_lims"] == [0.26, 0.12]
    train, val, info = split_train_val(trials, seed=3)
    assert len(train) == 6 and len(val) == 3
    assert sorted(t.condition for t in val) == sorted(CONDITIONS)          # exactly one per condition
    assert not ({t.name for t in train} & {t.name for t in val})
    _, val3, _ = split_train_val(trials, val_repeat=3)
    assert all(t.repeat == 3 for t in val3)


def test_replay_reproduces_generator_and_targets(session):
    trials = load_session(session)
    rep = PaddleReplayer(build_replay_sim_config(load_base_config(), session_attrs(trials)))
    # the recorded desired pose must be the sim's own target mapping
    for t in trials:
        for k in range(t.n_steps):
            assert np.allclose(rep.target_from(t.pose[k], t.actions[k]), t.desired[k], atol=1e-9)
    e_true = evaluate_trials(rep, trials, TRUE)
    assert e_true["mean_pos_err_mm"] < 1e-3, e_true["mean_pos_err_mm"]   # float32 actions in the file
    e_wrong = evaluate_trials(rep, trials, PlantParams(1500.0, 0.0, 10.0, 3000.0))
    assert e_wrong["mean_pos_err_mm"] > 5.0
    assert set(e_wrong["per_condition"]) == set(CONDITIONS) and len(e_wrong["per_trial"]) == 9
    # density change takes effect without rebuilding the env
    e_heavy = evaluate_trials(rep, trials, PlantParams(TRUE.kp, TRUE.ki, TRUE.kd, 6000.0))
    assert e_heavy["mean_pos_err_mm"] > 1.0


def test_gain_bounds_roundtrip():
    b = GainBounds()
    for p in (PlantParams(9000.0, 0.0, 50.0), PlantParams(600.0, 12345.0, 2000.0)):
        q = b.to_gains(b.to_unit(p))
        assert np.isclose(q.kp, p.kp, rtol=1e-6) and np.isclose(q.kd, p.kd, rtol=1e-6) and np.isclose(q.ki, p.ki, rtol=1e-6, atol=1e-6)
    assert b.to_gains([0.5, 0.0, 0.5]).ki == 0.0 and b.to_gains([0.5, 0.5, 0.0]).kd == 0.0


def test_cmaes_improves_from_wrong_start(session):
    trials = load_session(session)
    train, val, _ = split_train_val(trials, seed=0)
    sim_cfg = build_replay_sim_config(load_base_config(), session_attrs(trials))
    x0 = PlantParams(1500.0, 0.0, 10.0, 3000.0)
    ev = CandidateEvaluator(sim_cfg, train, val, 3000.0, workers=1)
    try:
        res = run_cmaes(ev, x0, sigma0=0.3, popsize=8, max_iter=12, seed=1, log=None)
    finally:
        ev.close()
    rep = PaddleReplayer(sim_cfg)
    e0 = evaluate_trials(rep, val, x0)["mean_pos_err_mm"]
    e1 = evaluate_trials(rep, val, PlantParams(res.best.kp, res.best.ki, res.best.kd, 3000.0))["mean_pos_err_mm"]
    assert res.n_evaluations == 8 * len(res.generation_best) and len(res.candidates) == res.n_evaluations
    assert e1 < 0.5 * e0, (e0, e1)
    assert np.isclose(res.best_val_err_mm, e1, atol=1e-6)


def test_cli_end_to_end(session, tmp_path):
    from sysid.paddle_pid.code import fit_pid_cmaes
    out = tmp_path / "fit"
    fit_pid_cmaes.main(["--input-dir", str(session), "--out", str(out), "--x0", "1500", "0", "10",
                        "--popsize", "6", "--max-iter", "4", "--workers", "2", "--no-plots"])
    for rel in ("split.json", "fit_result.json", "candidates.csv", "evaluations.json", "per_trial.csv",
                "sim_config_fitted.yaml", "sim_config_replay.yaml", "summary.md"):
        assert (out / rel).exists(), rel
    r = json.load(open(out / "fit_result.json"))
    assert r["n_evaluations"] == 6 * 4 and r["val_err_mm"]["fitted"] <= r["val_err_mm"]["canonical"] + 1e-9
    assert set(r["percentile_validation"]["percentiles"]) == {"50", "75", "90"}


def test_overlay_rendering(session, tmp_path):
    from sysid.paddle_pid.code.overlay import SceneRenderer, write_gif, write_png, mosaic
    trials = load_session(session)
    rep = PaddleReplayer(build_replay_sim_config(load_base_config(), session_attrs(trials)))
    ev = evaluate_trials(rep, trials[:2], TRUE, keep_trajectories=True)
    scene = SceneRenderer(rep)
    t = trials[0]
    results = {"canonical": ev["trajectories"][t.name], "cmaes": ev["trajectories"][t.name]}
    # a real-frame point maps to the same pixel as the env's own renderer maps the sim paddle
    u, v = scene.px(t.pose[0])
    assert 0 <= u < 360 and 0 <= v < scene.r.render_length
    img = scene.trial_summary_image(t, results, width=200)
    assert img.shape[1] == 200 and img.shape[2] == 3
    frames = scene.trial_frames(t, results, width=160, hold_last=2)
    assert len(frames) == t.n_steps + 2 and frames[0].shape[1] == 160
    write_gif(frames, tmp_path / "t.gif", fps=10)
    write_png(mosaic([img, img], ncols=2), tmp_path / "m.png")
    assert (tmp_path / "t.gif").stat().st_size > 0 and (tmp_path / "m.png").stat().st_size > 0


def test_render_overlays_cli(session, tmp_path):
    from sysid.paddle_pid.code import render_overlays
    out = tmp_path / "ov"
    render_overlays.main(["--input-dir", str(session), "--out", str(out), "--gains", "true", "6000", "200", "120",
                          "--gains", "wrong", "1500", "0", "10", "--trials", "val", "--width", "160", "--no-gifs"])
    for rel in ("per_trial_errors.md", "per_trial_errors.csv", "mosaic_val.png", "plots/per_trial_errors.png",
                "plots/per_trial_step_errors.png"):
        assert (out / rel).exists(), rel
    assert len(list((out / "png").glob("*.png"))) == 3
