# Air Hockey Table Parameters
air_hockey:
  obs_type: 'paddle'
  simulator_params:
    absorb_target: false
    length: 1.9304
    width: 0.8636
    puck_radius: 0.03175
    paddle_radius: 0.0508
    block_width: 0.0554
    force_scaling: 1000
    paddle_damping: 3
    puck_damping: 0.5
    paddle_density: 2500
    puck_density: 250
    block_density: 1000
    render_size: 360
    gravity: -0.5
    max_force_timestep: 100 # max force we can apply at one timestep
  
  simulator: box2d # or robosuite
  max_timesteps: 300
  # reward_type: 'goal_position_velocity'
  task: 'paddle_goal_position_neg'
  num_paddles: 1
  num_pucks: 0
  num_blocks: 0
  num_obstacles: 0
  num_targets: 0
  goal_max_x_velocity: 1 # min is -goal_max_x_velocity
  goal_min_y_velocity: 1
  goal_max_y_velocity: 5

  terminate_on_out_of_bounds: false
  terminate_on_enemy_goal: false
  terminate_on_puck_stop: false
  truncate_rew: -1
  wall_bumping_rew: -1
  direction_change_rew: -0.05
  horizontal_vel_rew: -0.1
  diagonal_motion_rew: -0.1
  stand_still_rew: 0.01

  # Reward region parameters
  num_negative_reward_regions: 10
  negative_reward_range: [-1,-1]
  reward_region_shapes: ["circle", "rect", "ellipse"]
  reward_region_scale_range: [0,0]
  reward_normalized_radius_min: [0.05,0.05]
  reward_normalized_radius_max: [0.25,0.25]  
  # reward_velocity_limits
  # reward_movement_types
# Training Parameters
n_training_steps: 1000000
model_save_filepath: model # will be saved same dir as tb_log_dir
vec_normalize_save_filepath: vec_normalize.pkl
tb_log_dir: baseline_models
tb_log_name: air_hockey_agent
gamma: 0.99
seed: [0, 1, 2, 3, 4]
n_threads: 1
algorithm: ppo

n_eval_eps: 30
eval_freq: 5000

# this parameter is only used when evaluating demonstrations
print_reward: false

# None of the below are integrated, but examples of what could be added to the config file
# num_envs: 16
# num_steps: 2048
# num_epochs: 10
# num_minibatches: 32
# learning_rate: 3e-4
# gamma: 0.99
# gae_lambda: 0.95
# clip_range: 0.2
# vf_coef: 0.5
# ent_coef: 0.01
# max_grad_norm: 0.5
# value_clip: true
# log_interval: 10
# save_interval: 100