air_hockey:
  diagonal_motion_rew: -0.1
  direction_change_rew: -0.05
  goal_max_x_velocity: 1
  goal_max_y_velocity: 5
  goal_min_y_velocity: 1
  horizontal_vel_rew: -0.1
  max_timesteps: 300
  n_training_steps: 1000000
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  obs_type: history
  return_goal_obs: false
  seed: 0
  simulator: box2d
  simulator_params:
    absorb_target: false
    block_density: 1000
    block_width: 0.0554
    force_scaling: 1000
    gravity: -0.5
    length: 1.9304
    max_force_timestep: 100
    paddle_damping: 3
    paddle_density: 2500
    paddle_radius: 0.0508
    puck_damping: 0.5
    puck_density: 250
    puck_radius: 0.03175
    render_size: 360
    seed: 0
    wall_bounce_scale: 0.01
    width: 0.8636
  stand_still_rew: 0.01
  task: puck_touch
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: false
  terminate_on_puck_hit_bottom: true
  terminate_on_puck_hit_paddle: true
  terminate_on_puck_pass_paddle: true
  terminate_on_puck_stop: false
  truncate_rew: -1
  wall_bumping_rew: -1
algorithm: ppo
eval_freq: 5000
gamma: 0.99
model_save_filepath: model
n_eval_eps: 30
n_threads: 20
n_training_steps: 1000000
print_reward: false
seed: 0
tb_log_dir: baseline_models
tb_log_name: air_hockey_agent
vec_normalize_save_filepath: vec_normalize.pkl
