action_force_attenuation_max: null
action_force_attenuation_min: null
action_force_attenuation_prob: null
action_scale: 1.0
actor_updates_per_iteration: 6
agent_hidden_layer_size: 64
agent_hidden_size: null
agent_num_hidden_layers: 2
args_file: scripts/smooth_policy/amp_history/configs/td3/td3_recommended.yaml
axis_alignment_reward_weight: 0.0
batch_size: 512
buffer_size: 100000
checkpoint_interval: 25000
config: scripts/smooth_policy/amp_history/configs/new_juggle/sysid_best_params_hist5.yaml
critic_failure_sample_fraction: 0.7
critic_per_fraction: 0.7
critic_success_sample_fraction: 0.3
critic_uniform_fraction: 0.3
device: cuda:3
enable_action_force_attenuation: false
enable_puck_delay_interpolation: true
estop_motion_reward_penalty: -5.0
eval_mode: false
exploration_direction_y_component_weight: 2
exploration_noise: 0.1
exploration_policy_takeover_args_path: args.yaml
exploration_policy_takeover_config_path: config.yaml
exploration_policy_takeover_enabled: false
exploration_policy_takeover_model_path: model2.pth
exploration_pre_contact_hit_variant_chance: 0.0
exploration_pre_contact_hit_variant_distance_threshold: 0.25
exploration_pre_contact_hit_variant_min_upward_displacement_x: 0.12
exploration_pre_contact_hit_variant_scale_max: 1.5
exploration_pre_contact_hit_variant_scale_min: 0.5
exploration_pre_contact_hit_variant_steps: 5
exploration_pre_learning_action_source: random
exploration_primitive_chance: 0.05
exploration_primitive_chance_anneal_steps: 200000
exploration_primitive_chance_pre_learning_starts: null
exploration_primitive_chance_start: 0.15
exploration_primitive_steps: 5
exploration_primitive_weight_anneal_policy_takeover: 0.0
exploration_primitive_weight_anneal_same_direction: 1.0
exploration_primitive_weight_anneal_stand_still: 0.2
exploration_primitive_weight_anneal_target_position_directional: 1.0
exploration_primitive_weight_anneal_y_aligned: 1.0
exploration_primitive_weight_policy_takeover: 0.0
exploration_primitive_weight_same_direction: 1.0
exploration_primitive_weight_stand_still: 0.2
exploration_primitive_weight_target_position_directional: 1.0
exploration_primitive_weight_y_aligned: 1.0
exploration_same_direction_max_angle_deg: null
exploration_same_direction_max_magnitude: null
exploration_same_direction_min_angle_deg: null
exploration_same_direction_min_magnitude: null
exploration_target_position_delta_x: 0.26
exploration_target_position_delta_y: 0.12
exploration_target_position_directional_max_angle_deg: null
exploration_target_position_directional_max_magnitude: null
exploration_target_position_directional_min_angle_deg: null
exploration_target_position_directional_min_magnitude: null
exploration_target_position_max_distance: 0.5
exploration_target_position_min_distance: 0.2
exploration_target_position_steps: 5
exploration_y_aligned_max_angle_deg: null
exploration_y_aligned_max_magnitude: null
exploration_y_aligned_min_angle_deg: null
exploration_y_aligned_min_magnitude: null
failure_buffer_size: 70000
full_checkpoint_load: full_resume
gravity: null
h_transform_eps: 0.001
jerk_at_one: 8.0
jerk_at_zero: 20.0
jerk_reward_weight: 0.5
learning_starts: 20000
log_parent_dir: runs/td3/hist_motion_collision/hist5_motion0p01
model_path: null
motion_gamma: 0.85
motion_reward_weight: 0.01
noise_clip: 0.5
num_envs: 1
paddle_damping: null
paddle_density: null
paddle_restitution: null
per_alpha: 0.6
per_beta_anneal_steps: 200000
per_beta_end: 1.0
per_beta_start: 0.4
per_enabled: true
per_eps: 1.0e-06
policy_frequency: 1
policy_lr: 0.0003
policy_noise: 0.2
puck_damping: null
puck_delay_interpolation_max: null
puck_delay_interpolation_min: null
puck_density: null
puck_restitution: null
q_frequency: 1
q_hidden_layer_size: 64
q_hidden_size: null
q_lr: 0.001
q_num_hidden_layers: 2
q_updates: 25
q_weight_decay: 0.0001
recent_episode_window_size: 500
run_name: hist5_motion0p01
sample_gif_interval: 10000
sample_gif_max_storage_mb: 50.0
save_replay_buffer: true
seed: 0
stand_still_reward_weight: 0.1
stand_still_threshold: 0.015
success_buffer_size: 30000
success_top_fraction: 0.2
target_network_frequency: 10
task_gamma: 0.985
task_reward_weight: 1.0
tau: 0.005
temporal_alignment_horizon: 4
temporal_alignment_reward_weight: 0.0
total_timesteps: 1000000
use_last_action_in_policy_state: true
velocity_at_one: 0.2
velocity_at_zero: 0.6
velocity_reward_weight: 0.5
watch_episode_interval: 50
watch_ring_size: 10
