acceleration_penalty_weight: 0.0
action_magnitude_reward_scale: 0.4
action_scale: 1
actor_logstd_on_model_load: 0.0
agent_hidden_layer_size: 64
agent_num_hidden_layers: 5
amp_components_path: null
anneal_lr: false
args_file: scripts/smooth_policy/amp_history/configs/ppo/amp_larger.yaml
batch_size: 4096
bc_kl_decay_iters: 200
bc_kl_weight: 0.01
bc_policy_path: null
clip_coef: 0.2
clip_vloss: false
config: scripts/smooth_policy/amp_history/configs/new_juggle/pid_noise_constant_upper_half_custom_sim_params.yaml
demo_data_path: scripts/smooth_policy/amp_history/amp_training/amp_data/amp_paddle_puck_dataset.pt
device: cuda:0
disc_batch_size: 256
disc_debug_interval: 5000
disc_grad_penalty: 5.0
disc_hidden_layer_size: 64
disc_learning_rate: 0.0001
disc_logit_reg: 0.01
disc_num_hidden_layers: 3
disc_replay_buffer_size: 50000
disc_replay_samples: 2048
disc_reward_warmup_iters: 10
disc_reward_warmup_value: 0.4
disc_reward_weight: 0.5
disc_weight_decay: 0.0001
discriminator_path: null
ent_coef: 0.0
gae_lambda: 0.95
gamma: 0.99
jerk_penalty_weight: 0.0
learning_rate: 0.0001
log_parent_dir: runs/new_architecture_ppo_disc/test/run
max_grad_norm: 0.5
minibatch_size: 32
model_path: null
motion_norm_clip: 10.0
motion_norm_eps: 1.0e-06
motion_norm_update_online: true
motion_norm_warmup_steps: 2048
norm_adv: true
num_discriminator_updates: 3
num_envs: 8
num_iterations: 5000
num_steps: 512
puck_downward_positive_direction: 1.0
puck_downward_speed_max: 0.75
puck_noise_std: 0.03
puck_speed_dt: 0.05
puck_vertical_axis: 0
puck_vertical_pos_max: 1.0
puck_vertical_pos_min: -1.0
ref_max_episode_steps: 30
reference_data_path: null
reset_actor_logstd_on_model_load: false
run_name: pid_test
seed: 0
target_kl: null
task_reward_weight: 0.5
temporal_alignment_horizon: 4
temporal_alignment_reward_scale: 0.4
update_epochs: 10
use_action_discriminator: false
use_last_action_in_policy_state: true
use_puck_discriminator: false
use_reference_state_init: false
velocity_penalty_weight: 0.0
vf_coef: 0.5
