from .paddle_reach_position_negative_regions_reward import AirHockeyPaddleReachPositionNegRegionsReward
from .paddle_reach_position_reward import AirHockeyPaddleReachPositionReward
from .paddle_reach_position_velocity_reward import AirHockeyPaddleReachPositionVelocityReward
from .puck_goal_position_dynamic_negative_regions_reward import AirHockeyPuckGoalPositionDynamicNegRegionsReward
from .puck_goal_position_reward import AirHockeyPuckGoalPositionReward
from .puck_goal_position_velocity_reward import AirHockeyPuckGoalPositionVelocityReward