"""
Aggregate results from a TD3 sweep into a summary CSV and/or wandb table.

Reads each run sub-directory under log_parent_dir and collects:
  - Sweep hyperparameters from args.yaml
  - Training metrics from TensorBoard event files
  - Eval metrics from rollout/metadata.yaml and rollout/per_timestep.csv
    (populated if you ran the eval bash script generated by generate_sweep.py)

Usage:
    # Via sweep YAML (auto-reads log_parent_dir, limits columns to swept params)
    uv run scripts/smooth_policy/amp_history/amp_training/td3/helper/aggregate_sweep.py \\
        --sweep-file scripts/smooth_policy/amp_history/configs/td3/example_reward_sweep.yaml \\
        --output-csv sweep_results.csv

    # Directly at a log directory (includes all args as columns)
    uv run scripts/smooth_policy/amp_history/amp_training/td3/helper/aggregate_sweep.py \\
        --sweep-dir /data2/calebc/air_hockey/reward_sweep \\
        --output-csv sweep_results.csv

    # Upload a wandb summary table
    uv run ... --sweep-file ... --output-csv sweep_results.csv \\
        --wandb-project my-project --wandb-entity my-entity
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from typing import Any

import yaml


# ---------------------------------------------------------------------------
# TensorBoard helpers
# ---------------------------------------------------------------------------

def _read_tb_scalars(run_dir: str, tag: str) -> list[tuple[int, float]]:
    """Return (step, value) pairs for a TensorBoard scalar tag. Returns [] on any failure."""
    try:
        from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
    except ImportError:
        return []
    try:
        ea = EventAccumulator(run_dir, size_guidance={"scalars": 0})
        ea.Reload()
        available = ea.Tags().get("scalars", [])
        if tag not in available:
            return []
        return [(e.step, e.value) for e in ea.Scalars(tag)]
    except Exception:
        return []


def _final(pairs: list[tuple[int, float]]) -> float | None:
    return pairs[-1][1] if pairs else None


def _max(pairs: list[tuple[int, float]]) -> float | None:
    return max(v for _, v in pairs) if pairs else None


# ---------------------------------------------------------------------------
# Per-run aggregation
# ---------------------------------------------------------------------------

def _aggregate_run(run_dir: str, param_keys: list[str] | None) -> dict[str, Any] | None:
    """
    Collect metrics for one run directory. Returns None if args.yaml is missing
    (meaning it's not a valid run dir).
    """
    args_yaml = os.path.join(run_dir, "args.yaml")
    if not os.path.isfile(args_yaml):
        return None

    with open(args_yaml) as f:
        run_args: dict = yaml.safe_load(f) or {}

    row: dict[str, Any] = {
        "run_dir": run_dir,
        "run_name": run_args.get("run_name", os.path.basename(run_dir)),
    }

    # Hyperparams: either the explicit swept keys, or every key in args.yaml
    for k in (param_keys or sorted(run_args.keys())):
        row[k] = run_args.get(k)

    # --- TensorBoard training metrics ---
    rolling_pairs = _read_tb_scalars(run_dir, "charts/rolling2k_avg_episode_return")
    episode_pairs = _read_tb_scalars(run_dir, "charts/episodic_return")

    row["final_rolling_return"] = _final(rolling_pairs)
    row["max_rolling_return"] = _max(rolling_pairs)
    row["final_episode_return"] = _final(episode_pairs)
    row["max_episode_return"] = _max(episode_pairs)
    row["tb_steps"] = rolling_pairs[-1][0] if rolling_pairs else None

    # --- Eval rollout (produced by collect_policy_data.py --run-dir <run_dir>) ---
    rollout_dir = os.path.join(run_dir, "rollout")
    eval_meta_path = os.path.join(rollout_dir, "metadata.yaml")
    if os.path.isfile(eval_meta_path):
        with open(eval_meta_path) as f:
            eval_meta: dict = yaml.safe_load(f) or {}
        coll = eval_meta.get("collection", {})
        row["eval_episodes_completed"] = coll.get("episodes_completed")
        row["eval_total_timesteps"] = coll.get("total_timesteps_collected")

    per_step_csv = os.path.join(rollout_dir, "per_timestep.csv")
    if os.path.isfile(per_step_csv):
        rewards: list[float] = []
        episode_returns: dict[int, float] = {}  # episode_index -> cumulative reward
        try:
            with open(per_step_csv, newline="") as f:
                reader = csv.DictReader(f)
                for r in reader:
                    if "reward" in r and r["reward"]:
                        try:
                            rew = float(r["reward"])
                            rewards.append(rew)
                            ep_idx = int(r.get("episode_index", 0))
                            episode_returns[ep_idx] = episode_returns.get(ep_idx, 0.0) + rew
                        except ValueError:
                            pass
        except Exception:
            pass

        row["eval_mean_step_reward"] = sum(rewards) / len(rewards) if rewards else None
        returns = list(episode_returns.values())
        row["eval_mean_episode_return"] = sum(returns) / len(returns) if returns else None
        row["eval_max_episode_return"] = max(returns) if returns else None

    return row


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def aggregate_sweep(
    sweep_dir: str,
    param_keys: list[str] | None = None,
) -> list[dict[str, Any]]:
    """
    Walk sweep_dir, read each run's metrics, and return a list of row dicts
    (one per valid run sub-directory).

    Args:
        sweep_dir:  Path to the log_parent_dir that contains per-run sub-directories.
        param_keys: Which arg names to include as hyperparameter columns.
                    If None, all args are included (can be very wide).
    """
    if not os.path.isdir(sweep_dir):
        raise FileNotFoundError(f"sweep_dir not found: {sweep_dir}")

    rows = []
    for entry in sorted(os.scandir(sweep_dir), key=lambda e: e.name):
        if not entry.is_dir():
            continue
        row = _aggregate_run(entry.path, param_keys)
        if row is not None:
            rows.append(row)

    return rows


def write_csv(rows: list[dict], output_path: str) -> None:
    if not rows:
        print("No runs found — CSV not written.", file=sys.stderr)
        return
    fieldnames = list(rows[0].keys())
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} row(s) to {output_path}")


def _print_table(rows: list[dict], param_keys: list[str] | None) -> None:
    """Print a compact TSV to stdout."""
    metric_cols = [
        "final_rolling_return",
        "max_rolling_return",
        "eval_mean_episode_return",
        "tb_steps",
    ]
    param_cols = param_keys or []
    header = ["run_name"] + param_cols + metric_cols
    print("\t".join(header))
    for row in rows:
        print("\t".join("" if row.get(c) is None else str(row.get(c)) for c in header))


def upload_to_wandb(
    rows: list[dict],
    project: str,
    entity: str | None,
    sweep_dir: str,
) -> None:
    import wandb

    run = wandb.init(
        project=project,
        entity=entity,
        job_type="sweep_aggregate",
        name=f"aggregate_{os.path.basename(sweep_dir.rstrip('/'))}",
        config={"sweep_dir": sweep_dir, "num_runs": len(rows)},
    )
    if not rows:
        wandb.finish()
        return

    columns = list(rows[0].keys())
    table = wandb.Table(columns=columns)
    for row in rows:
        table.add_data(*[row.get(c) for c in columns])

    wandb.log({"sweep_results": table})
    wandb.finish()
    print(f"Uploaded {len(rows)}-row table to wandb project '{project}' (run: {run.name})")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Aggregate TD3 sweep run results into a CSV / wandb table."
    )
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument(
        "--sweep-file",
        help="Path to sweep YAML. Auto-reads log_parent_dir and restricts columns to swept params.",
    )
    src.add_argument(
        "--sweep-dir",
        help="Path to the sweep log parent directory (use when you have no sweep YAML).",
    )
    parser.add_argument("--output-csv", default=None, help="Path to write the output CSV.")
    parser.add_argument(
        "--param-keys",
        nargs="*",
        default=None,
        help="Explicit list of arg names to use as hyperparameter columns. "
             "Defaults to params listed in the sweep YAML (or all args if --sweep-dir is used).",
    )
    parser.add_argument("--wandb-project", default=None, help="Upload summary table to this wandb project.")
    parser.add_argument("--wandb-entity", default=None, help="wandb entity/team.")
    args = parser.parse_args()

    sweep_cfg: dict = {}
    if args.sweep_file:
        if not os.path.isfile(args.sweep_file):
            print(f"ERROR: sweep file not found: {args.sweep_file}", file=sys.stderr)
            sys.exit(1)
        with open(args.sweep_file) as f:
            sweep_cfg = yaml.safe_load(f) or {}
        if "log_parent_dir" not in sweep_cfg:
            print("ERROR: sweep YAML must contain 'log_parent_dir'.", file=sys.stderr)
            sys.exit(1)
        sweep_dir = sweep_cfg["log_parent_dir"]
        param_keys = args.param_keys if args.param_keys is not None else list(sweep_cfg.get("params", {}).keys())
    else:
        sweep_dir = args.sweep_dir
        param_keys = args.param_keys  # may be None → include all

    if not os.path.isdir(sweep_dir):
        print(f"ERROR: sweep dir not found: {sweep_dir}", file=sys.stderr)
        sys.exit(1)

    rows = aggregate_sweep(sweep_dir, param_keys=param_keys)
    print(f"Found {len(rows)} run(s) in {sweep_dir}")

    if args.output_csv:
        write_csv(rows, args.output_csv)
    else:
        if rows:
            _print_table(rows, param_keys)
        else:
            print("No valid runs found.")

    if args.wandb_project:
        upload_to_wandb(rows, args.wandb_project, args.wandb_entity, sweep_dir)


if __name__ == "__main__":
    main()
