diagonal_motion_rew: -0.1
direction_change_rew: -0.05
goal_max_x_velocity: 1
goal_max_y_velocity: 5
goal_min_y_velocity: 1
horizontal_vel_rew: -0.1
max_timesteps: 300
n_training_steps: 1000000
num_blocks: 0
num_obstacles: 0
num_paddles: 1
num_pucks: 1
num_targets: 0
obs_type: history
return_goal_obs: false
seed:
- 0
- 1
- 2
- 3
- 4
simulator: box2d
simulator_params:
  absorb_target: false
  action_x_scaling: 1.108854046182425
  action_y_scaling: 0.7325506641500633
  block_density: 500
  block_width: 0.0254
  force_scaling: 1000
  gravity: -0.4530242129449666
  length: 1.9304
  max_force_timestep: 36.20022976369259
  paddle_damping: 7.029979658078075
  paddle_density: 2241.0772644878925
  paddle_radius: 0.0508
  puck_damping: 0.7591223285015498
  puck_density: 205.06926370158365
  puck_radius: 0.03175
  render_size: 360
  wall_bounce_scale: 0.03718781583246066
  width: 0.8636
stand_still_rew: 0.01
task: puck_velocity
terminate_on_enemy_goal: true
terminate_on_out_of_bounds: true
terminate_on_puck_hit_bottom: true
terminate_on_puck_hit_paddle: false
terminate_on_puck_pass_paddle: true
terminate_on_puck_stop: false
truncate_rew: -1
wall_bumping_rew: -1
