base_goal_radius: 0.05
diagonal_motion_rew: -0.1
direction_change_rew: -0.05
goal_max_x_velocity: 1
goal_max_y_velocity: 5
goal_min_y_velocity: 1
goal_radius_type: fixed
horizontal_vel_rew: -0.1
max_timesteps: 300
n_training_steps: 1000000
num_blocks: 0
num_obstacles: 0
num_paddles: 1
num_pucks: 0
num_targets: 0
obs_type: paddle
return_goal_obs: false
seed:
- 0
- 1
- 2
- 3
- 4
simulator: box2d
simulator_params:
  absorb_target: false
  action_x_scaling: 1.1688480102219911
  action_y_scaling: 0.6969074673990617
  block_density: 1000
  block_width: 0.0554
  force_scaling: 1000
  gravity: -0.5
  length: 1.9304
  max_force_timestep: 31.42814170358874
  paddle_damping: 6.997091556730007
  paddle_density: 1963.6403092674977
  paddle_radius: 0.0508
  puck_damping: 0.5
  puck_density: 250
  puck_radius: 0.03175
  render_size: 360
  wall_bounce_scale: 0.02
  width: 0.8636
stand_still_rew: 0.01
task: paddle_reach_position
terminate_on_enemy_goal: false
terminate_on_out_of_bounds: false
terminate_on_puck_stop: false
truncate_rew: -1
wall_bumping_rew: -1
