air_hockey:
  max_timesteps: 250
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  obs_type: history
  seed: 0
  puck_spawn_near_paddle_prob: 0.15
  puck_near_paddle_offset_min_m: 0.025
  puck_near_paddle_offset_max_m: 0.05
  puck_near_paddle_horizontal_std_m: 0.015
  puck_near_paddle_speed_min_m_s: 0.0
  puck_near_paddle_speed_max_m_s: 0.2
  puck_linear_top_spawn_goal_cutoff_x: null
  puck_linear_top_spawn_center_cutoff_x: 0.2
  puck_linear_top_spawn_speed_min: 0.0
  puck_linear_top_spawn_speed_max: 0.5
  simulator: box2d
  simulator_params:
    absorb_target: false
    enable_puck_delay_interpolation: true
    block_density: 1000
    block_width: 0.0254
    length: 1.9304
    max_force_timestep: 10000
    paddle_radius: 0.0508
    force_scaling: 0.99
    paddle_damping: 17
    paddle_density: 3000
    gravity: -0.661
    puck_damping: 0.178
    puck_density: 3000
    puck_restitution: 1.09145
    paddle_restitution: 1.0
    side_wall_restitution: 0.99
    end_wall_restitution: 0.7
    puck_radius: 0.03175
    render_size: 360
    seed: 0
    width: 0.8636
    pid_kp: 9000
    pid_kd: 50
    pid_ki: 0.0
    hist_len: 2
    puck_noise: true
    puck_noise_std: 0.01
    enable_random_occlusions: true
    random_occlusion_rate: 0.05
    random_occlusion_length_weights:
    - 75
    - 39
    - 18
    - 9
    - 4
    - 2
    - 1
    enable_action_delay: false
    enable_observation_delay: true
    delay_seconds: 0.025
  task: puck_juggle_upper_half_reward
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: false
  terminate_on_puck_hit_bottom: true
  terminate_on_puck_hit_paddle: false
  terminate_on_puck_pass_paddle: true
  terminate_on_puck_stop: false
