air_hockey:
  obs_type: 'history'
  diagonal_motion_rew: -0.1
  direction_change_rew: -0.05
  goal_max_x_velocity: 1
  goal_max_y_velocity: 5
  goal_min_y_velocity: 1
  horizontal_vel_rew: -0.1
  max_timesteps: 300
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  simulator: robosuite
  simulator_params:
    block_width: 0.0254
    depth: 0.101
    has_renderer: true
    length: 2.1104
    max_paddle_vel: 10
    max_puck_vel: 10
    paddle_radius: 0.0508
    puck_damping: 0.0
    puck_density: 250
    puck_radius: 0.03175
    render_size: 360
    rim_width: 0.045
    table_elevation: 0.7874
    table_tilt: 0.09
    width: 1.0436
  stand_still_rew: 0.01
  task: goal_position
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: true
  terminate_on_puck_stop: true
  truncate_rew: -1
  wall_bumping_rew: -1
algorithm: sac
curriculum:
  model: ''
eval_freq: 5000
gamma: 0.99
model_save_filepath: model
n_eval_eps: 30
n_threads: 1
n_training_steps: 1000000
print_reward: false
seed:
- 0
- 1
- 2
- 3
- 4
tb_log_dir: baseline_models
tb_log_name: air_hockey_agent
vec_normalize_save_filepath: vec_normalize.pkl
