air_hockey:
  diagonal_motion_rew: -0.1
  direction_change_rew: -0.05
  goal_max_x_velocity: 1
  goal_max_y_velocity: 5
  goal_min_y_velocity: 1
  horizontal_vel_rew: -0.1
  max_timesteps: 300
  n_training_steps: 10000
  simulator: robosuite
  simulator_params:
    # 57: <geom name="surface" type="box" material="white" size="length width 0.0505" pos="0 0 -0.0505"
    length: 2.1104
    width: 1.0436
    depth: 0.101
    rim_width: 0.045
    table_tilt: 0.09
    table_elevation: 0.7874
    # 102: <geom pos="0 0 -0.2" name="puck" type="cylinder" material="red" size="puck_radius 0.009" condim="4" priority="0" group="1"/>
    puck_radius: 0.03175
    paddle_radius: 0.0508
    block_width: 0.0254 # who?
    #97: <joint name="puck_x" type="slide" axis="1 0 0" damping="0.01" limited="false"/>
    #98: <joint name="puck_y" type="slide" axis="0 1 0" damping="0.01" limited="false"/>
    puck_damping: 0.01
    puck_density: 3530
    max_paddle_vel: 2
    max_puck_vel: 2
    render_size: 360
    has_renderer: true
  stand_still_rew: 0.01
  task: 'puck_velocity'
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: true
  terminate_on_puck_stop: true
  truncate_rew: -1
  wall_bumping_rew: -1
gamma: 0.99
model_save_filepath: model
n_training_steps: 1000000
print_reward: false
seed: [0, 1, 2, 3, 4]
n_threads: 1
algorithm: ppo
tb_log_dir: baseline_models
tb_log_name: air_hockey_agent
vec_normalize_save_filepath: vec_normalize.pkl

n_eval_eps: 30
eval_freq: 5000
