actor_updates_per_iteration: 6
agent_hidden_layer_size: 128
agent_num_hidden_layers: 2
args_file: /home/air-hockey/daliu/air-hockey-rl/configs/td3/her/puck_goal_sysid_filter_hist2.yaml
batch_size: 512
buffer_size: 100000
checkpoint_eval_async: true
checkpoint_interval: 25000
compile_rollout_actor: true
compile_update: true
config: /home/air-hockey/daliu/air-hockey-rl/configs/new_juggle/tasks/sim_sysid_puck_goal_hist2.yaml
cql_alpha: 0.0
cql_n_random: 10
critic_failure_sample_fraction: 0.7
critic_per_fraction: 0.7
critic_success_sample_fraction: 0.3
critic_uniform_fraction: 0.3
device: cuda:2
eval_n_eps: 20
eval_n_eps_final: 100
eval_n_gifs: 1
exploration_action_delta_x: 0.26
exploration_action_delta_y: 0.12
exploration_direction_y_component_weight: 2
exploration_noise: 0.1
exploration_pre_learning_action_source: random
exploration_primitive_chance: 0.05
exploration_primitive_chance_anneal_steps: 200000
exploration_primitive_chance_pre_learning_starts: null
exploration_primitive_chance_start: 0.15
exploration_primitive_steps: 5
exploration_primitive_weight_anneal_same_direction: 3.0
exploration_primitive_weight_anneal_stand_still: 0.2
exploration_primitive_weight_same_direction: 3.0
exploration_primitive_weight_stand_still: 0.2
exploration_same_direction_max_angle_deg: null
exploration_same_direction_max_magnitude: null
exploration_same_direction_min_angle_deg: null
exploration_same_direction_min_magnitude: null
failure_buffer_size: 70000
full_checkpoint_load: full_resume
gamma: 0.975
h_transform_eps: 0.001
her_done_on_success: true
her_goal_filter: true
her_k: 4
her_strategy: future
learning_starts: 20000
log_parent_dir: /home/air-hockey/daliu/air-hockey-rl/runs/her/round2_20260910/puck_goal_sysid_filter_hist2
model_path: null
noise_clip: 0.5
num_critics: 2
num_envs: 1
per_alpha: 0.6
per_beta_anneal_steps: 200000
per_beta_end: 1.0
per_beta_start: 0.4
per_enabled: true
per_eps: 1.0e-06
policy_frequency: 1
policy_lr: 0.0003
policy_noise: 0.2
priority_age_decay: 0.0
q_frequency: 1
q_hidden_layer_size: 256
q_lr: 0.001
q_num_hidden_layers: 2
q_updates: 25
q_weight_decay: 0.0
recent_episode_window_size: 500
rollout_device: cpu
run_name: puck_goal_her_filter_hist2
sample_gif_interval: 10000
sample_gif_max_storage_mb: 50.0
save_replay_buffer: true
save_replay_buffer_intermediate: false
seed: 0
single_replay_buffer: true
stats_log_interval: 5000
success_buffer_size: 1000000
success_top_fraction: 0.5
target_critic_subset_size: null
target_network_frequency: 10
tau: 0.005
torch_num_threads: 1
total_timesteps: 1000000
train_metrics_log_interval: 20
use_cuda_graphs: true
use_last_action_in_policy_state: true
watch_episode_interval: 50
watch_ring_size: 10
