# Air Hockey Table Parameters
air_hockey:
  num_paddles: 1
  num_pucks: 1
  num_blocks: 0
  num_obstacles: 0
  num_targets: 0
  absorb_target: false
  use_cue: false
  length: 10
  width: 6
  paddle_radius: 0.4
  force_scaling: 200
  paddle_damping: 13
  max_goal_rew_radius: 2
  render_size: 360
  max_timesteps: 1000
  gravity: -20
  reward_type: 'goal_discrete'
  terminate_on_out_of_bounds: true
  terminate_on_enemy_goal: true
  truncate_rew: -1
  wall_bumping_rew: -0.1

print_reward: false
