# Air Hockey Table Parameters
air_hockey:
  simulator_params:
    num_paddles: 1
    num_pucks: 1
    num_blocks: 0
    num_obstacles: 0
    num_targets: 0
    absorb_target: false
    length: 1.9304
    width: 0.8636
    puck_radius: 0.03175
    paddle_radius: 0.0508
    block_width: 0.0254
    force_scaling: 1000
    paddle_damping: 10
    puck_damping: 1
    paddle_density: 1000
    puck_density: 250
    render_size: 360
    gravity: -0.5
    max_force_timestep: 250 # max force we can apply at one timestep
    render_size: 360

  simulator: box2d # or robosuite
  max_timesteps: 1000
  # reward_type: 'goal_position_velocity'
  reward_type: 'puck_vel'
  goal_max_x_velocity: 1 # min is -goal_max_x_velocity
  goal_min_y_velocity: 1
  goal_max_y_velocity: 5

  terminate_on_out_of_bounds: true
  terminate_on_enemy_goal: true
  truncate_rew: -0.5
  wall_bumping_rew: -0.1

# Training Parameters
n_training_steps: 50000
model_save_filepath: model # will be saved same dir as tb_log_dir
vec_normalize_save_filepath: vec_normalize.pkl
tb_log_dir: trained_models/gcrl
tb_log_name: air_hockey_gcrl
gamma: 0.99

# this parameter is only used when evaluating demonstrations
print_reward: false

# None of the below are integrated, but examples of what could be added to the config file
# num_envs: 16
# num_steps: 2048
# num_epochs: 10
# num_minibatches: 32
# learning_rate: 3e-4
# gamma: 0.99
# gae_lambda: 0.95
# clip_range: 0.2
# vf_coef: 0.5
# ent_coef: 0.01
# max_grad_norm: 0.5
# value_clip: true
# log_interval: 10
# save_interval: 100