"""Self-contained tests for the paddle–puck collision sysid module (no robot data needed).

* the speed estimator recovers the incoming / outgoing speeds and the contact time of a synthetic
  collision written in the recording layout (damped free flight on both sides, 30 Hz frames
  sampled at 20 Hz, an occlusion at the impact);
* the best-three selection drops a glancing hit and a carried puck;
* the Box2D collider reproduces the closed-form reduced-mass impulse where a single contact occurs;
* CMA-ES on collisions generated by the collider under a known (e, r) recovers the head-on gain.
"""

from __future__ import annotations

import sys
from pathlib import Path

import h5py
import numpy as np
import pytest

_REPO = Path(__file__).resolve().parents[4]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from sysid.paddle_puck_collision.code.dataset import load_session, split_train_val, session_attrs, parse_trial_name  # noqa: E402
from sysid.paddle_puck_collision.code.speeds import SpeedConfig, measure_all, calibrate_camera_lag, select_canonical  # noqa: E402
from sysid.paddle_puck_collision.code.sim_collision import (CollisionParams, HeadOnCollider, build_collision_sim_config,  # noqa: E402
                                                     closed_form_out_speed, evaluate_measurements, load_base_config)
from sysid.paddle_puck_collision.code.cmaes_fit import CandidateEvaluator, ParamBounds, run_cmaes  # noqa: E402

ATTRS = {"hist_len": 1, "move_lims": [0.26, 0.12], "workspace_lims": [-0.83, -0.42, -0.35, 0.39],
         "edge_lims": [0.8, 0.1, -0.188, -0.22], "center_offset_constant": 1.2}
G, GAM = 0.661, 0.178
LAG = 0.08
PAD_X0 = 0.766
D = 0.0508 + 0.03175


def _flight(t, p0, v0):
    """Damped free flight a = g − γ v in the observation frame (g towards +x)."""
    g = np.array([G, 0.0])
    e = np.exp(-GAM * t)
    return p0[None, :] + (v0 - g / GAM)[None, :] * ((1 - e) / GAM)[:, None] + (g / GAM)[None, :] * t[:, None]


def _write_trial(path, idx, height, delta, u_p, v_in, v_out, vy_out=0.0, dy=0.0, carried=False):
    """Synthetic trial: robot rows at 20 Hz, camera frames at 30 Hz delayed by LAG, one 2-frame occlusion at impact."""
    n_steps, dt = 40, 0.05
    t_step = 1.7e9 + dt * np.arange(n_steps)
    t0 = t_step[0]
    # paddle: ramps to u_p over 0.1 s, plateau for 20 steps, then stops
    tt = t_step - t0
    v_pad = np.where(tt < 0.1, u_p * tt / 0.1, u_p) * (tt < 1.0)
    x_pad = PAD_X0 - np.cumsum(np.r_[0.0, 0.5 * (v_pad[1:] + v_pad[:-1]) * dt])
    t_c = 0.25                                                   # robot-clock contact time
    x_pad_c = np.interp(t_c, tt, x_pad)
    x_c = x_pad_c - D
    y_c = -0.1 + dy
    # camera frames (true times), pre and post flight
    tf = np.arange(-0.6, 1.4, 1 / 30.0)
    pre = tf <= t_c
    puck = np.zeros((len(tf), 2))
    puck[pre] = _flight(tf[pre] - t_c, np.array([x_c, y_c]), np.array([v_in, 0.0]))
    if carried:                                                  # rides inside the paddle, as the real logs show
        puck[~pre, 0] = np.interp(tf[~pre], tt, x_pad) - D + 0.04
        puck[~pre, 1] = y_c
    else:
        puck[~pre] = _flight(tf[~pre] - t_c, np.array([x_c, y_c]), np.array([-v_out, vy_out]))
    occ = np.abs(tf - t_c) < 0.04
    t_cam = tf + LAG                                            # frame arrives LAG later
    # arm-wait frames: everything before the first step
    arm = t_cam < 0.0
    arm_rows = np.column_stack([t0 + t_cam[arm], puck[arm], occ[arm].astype(float)])
    tv = np.zeros((n_steps, 35))
    tv[:, 0] = t_step
    tv[:, 5], tv[:, 6] = x_pad - 1.2, -0.1
    tv[:, 11] = -v_pad
    for i in range(n_steps):                                    # the loop reads the latest arrived frame
        k = np.flatnonzero(t_cam <= tt[i])[-1]
        tv[i, 32:34] = puck[k]
        tv[i, 34] = float(occ[k])
    name = f"collision_{idx:03d}_h{height}_delta{delta:.2f}_y-0.100"
    with h5py.File(path / f"{name}.hdf5", "w") as f:
        f.create_dataset("train_vals", data=tv)
        f.create_dataset("arm_puck_track", data=arm_rows)
        f.create_dataset("actions", data=np.tile([-delta, 0.0], (n_steps, 1)).astype(np.float32))
        f.attrs["trial_name"] = name
        f.attrs["puck_height_label"] = {"top": "top", "3-4": "3/4", "1-2": "1/2"}[height]
        f.attrs["action_delta"] = delta
        f.attrs["y_offset"] = -0.1
        f.attrs["protective_stop"] = False
        f.attrs["aborted_at_step"] = -1
        for k, v in ATTRS.items():
            f.attrs[k] = v
    return name, t_c


@pytest.fixture(scope="module")
def session(tmp_path_factory):
    d = tmp_path_factory.mktemp("collision_session")
    truth = {}
    idx = 0
    for height, v_in in (("top", 1.1), ("1-2", 0.65)):
        for delta, u_p in ((1.0, 0.95), (0.0, 0.0)):
            for rep in range(3):
                v_out = 1.6 * (u_p + v_in) - v_in + 0.02 * rep
                name, t_c = _write_trial(d, idx, height, delta, u_p, v_in, v_out)
                truth[name] = dict(u_p=u_p, v_in=v_in, v_out=v_out, t_c=t_c)
                idx += 1
    # a glancing hit and a carried puck in the top / 1.00 condition (4th and 5th files)
    truth[_write_trial(d, idx, "top", 1.0, 0.95, 1.1, 1.0, vy_out=1.4, dy=0.05)[0]] = None
    truth[_write_trial(d, idx + 1, "top", 1.0, 0.95, 1.1, 0.9, carried=True)[0]] = None
    return d, truth


def test_parse_name():
    assert parse_trial_name("collision_012_h3-4_delta1.00_y-0.090") == (12, "3-4", 1.0, -0.09)


def test_speeds_recovered(session):
    d, truth = session
    trials = load_session(d)
    assert len(trials) == 14 and session_attrs(trials)["hist_len"] == 1
    cfg = SpeedConfig(gravity_x=G, damping=GAM)
    ms = measure_all(trials, cfg)
    lag = calibrate_camera_lag(trials, ms, cfg)
    assert abs(lag["lag_s"] - LAG) < 0.02, lag
    assert abs(lag["static_contact_gap_mean"] - D) < 0.01
    cfg.camera_lag_s = lag["lag_s"]
    ms = measure_all(trials, cfg)
    for m in ms:
        tr = truth[m.name]
        if tr is None:
            continue
        assert m.valid, (m.name, m.reason)
        assert abs(m.speed_in - tr["v_in"]) < 0.06, (m.name, m.speed_in, tr)
        assert abs(m.speed_out - tr["v_out"]) < 0.08, (m.name, m.speed_out, tr)
        assert abs(m.u_p - tr["u_p"]) < 0.05, (m.name, m.u_p, tr)
        assert abs(m.t_c - LAG - tr["t_c"]) < 0.04, (m.name, m.t_c, tr)


def test_selection_drops_bad_trials(session):
    d, truth = session
    trials = load_session(d)
    cfg = SpeedConfig(gravity_x=G, damping=GAM, camera_lag_s=LAG)
    ms = measure_all(trials, cfg)
    info = select_canonical(ms, per_condition=3)
    bad = [n for n, v in truth.items() if v is None]
    sel = info["htop_delta1.00"]
    assert sel["n_files"] == 5 and len(sel["selected"]) == 3
    assert not set(bad) & set(sel["selected"])
    reasons = {m.name: m.reason for m in ms if not m.valid}
    assert any("angle" in reasons.get(n, "") for n in bad), reasons
    assert any("separating" in reasons.get(n, "") or "re-contact" in reasons.get(n, "") for n in bad), reasons
    keep = [t for t in trials if t.name in {m.name for m in ms if m.selected}]
    train, val, info2 = split_train_val(keep, val_repeat=3)
    assert info2["n_val"] == 4 and info2["n_train"] == 8


@pytest.fixture(scope="module")
def collider():
    return HeadOnCollider(build_collision_sim_config(load_base_config(), ATTRS))


@pytest.mark.parametrize("e,r", [(1.09145, 2.56), (0.5, 1000.0), (0.84, 4.46)])
def test_collider_matches_closed_form(collider, e, r):
    p = CollisionParams(e, r)
    collider.set_params(p)
    for u_p, u_k in ((0.0, 1.2), (0.3, 1.0), (0.95, 1.1), (0.6, 0.6)):
        out = collider.run(u_p, u_k)
        assert out["n_contacts"] >= 1
        assert abs(out["u_p_actual"] - u_p) < 0.01
        assert abs(out["speed_out"] - closed_form_out_speed(p, u_p, u_k)) < 0.02, (u_p, u_k, out)


def test_cmaes_recovers_gain(collider):
    true = CollisionParams(0.7, 6.0)
    rng = np.random.RandomState(1)
    from sysid.paddle_puck_collision.code.speeds import CollisionMeasurement
    ms = []
    collider.set_params(true)
    for i in range(12):
        u_p, u_k = float(rng.choice([0.0, 0.3, 0.6, 0.95])), float(rng.uniform(0.6, 1.2))
        out = collider.run(u_p, u_k)
        ms.append(CollisionMeasurement(name=f"syn{i}", condition=f"c{i % 4}", height="top", action_delta=u_p, repeat=i // 4 + 1,
                                       valid=True, reason="", speed_in=u_k, speed_out=out["speed_out"], u_p=u_p))
    train, val = ms[:9], ms[9:]
    ev = CandidateEvaluator(collider.sim_cfg, train, val, workers=1)
    x0 = CollisionParams(1.09145, 2.56)
    assert evaluate_measurements(collider, train, x0)["rms_err"] > 0.05
    res = run_cmaes(ev, x0, bounds=ParamBounds(), sigma0=0.3, popsize=8, max_iter=15, seed=0, log=None)
    assert res.best_train_err < 0.01, res.best
    assert abs(res.best.gain() - true.gain()) < 0.02, (res.best, true.gain())
