#!/usr/bin/env python3
"""
Generate sim YAMLs for the zero-shot sim2real ablation sweep.

Each ablation starts from the canonical sysid_best_params_hist2.yaml (the
ground-truth source sim that hist2_motion0_v2 was trained on) and flips a
single knob (or set of knobs for the all-sysid-no-rand case). Patches are
expressed as exact string substitutions so a missing match aborts loudly
instead of silently producing a wrong YAML.

Run from repo root:
    .venv/bin/python scripts/smooth_policy/amp_history/configs/new_juggle/zeroshot_ablations/_generate.py
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[6]
BASE = REPO_ROOT / "scripts/smooth_policy/amp_history/configs/new_juggle/sysid_best_params_hist2.yaml"
OUT_DIR = Path(__file__).resolve().parent

HEADER_TEMPLATE = (
    "# Zero-shot sim2real ablation: {description}\n"
    "# Auto-generated by _generate.py from sysid_best_params_hist2.yaml.\n"
    "# Diff vs base:\n{diff_block}\n"
)


@dataclass
class Patch:
    """A single (old_substring, new_substring) edit that must match exactly once."""
    old: str
    new: str


@dataclass
class Ablation:
    name: str  # used as filename: sim_<name>.yaml
    description: str
    patches: list[Patch] = field(default_factory=list)


ABLATIONS: list[Ablation] = [
    Ablation(
        name="sysid_off",
        description=(
            "sysid OFF — revert gravity / puck_damping / paddle_density / pid gains "
            "to legacy off-the-shelf values from pid_noise_constant_upper_half_custom_sim_params.yaml."
        ),
        patches=[
            Patch(old="    paddle_density: 3000\n", new="    paddle_density: 1000\n"),
            Patch(old="    gravity: -0.661\n", new="    gravity: -0.65\n"),
            Patch(old="    puck_damping: 0.178\n", new="    puck_damping: 0.25\n"),
            Patch(old="    pid_kp: 9000\n", new="    pid_kp: 5000\n"),
            Patch(old="    pid_kd: 50\n", new="    pid_kd: 200\n"),
        ],
    ),
    Ablation(
        name="no_paddle_puck_strength",
        description="paddle-puck STRENGTH randomization OFF (direction kept on).",
        patches=[
            Patch(
                old="    enable_paddle_puck_strength_randomization: true\n",
                new="    enable_paddle_puck_strength_randomization: false\n",
            ),
        ],
    ),
    Ablation(
        name="no_paddle_puck_direction",
        description="paddle-puck DIRECTION randomization OFF (strength kept on).",
        patches=[
            Patch(
                old="    enable_paddle_puck_direction_randomization: true\n",
                new="    enable_paddle_puck_direction_randomization: false\n",
            ),
        ],
    ),
    Ablation(
        name="no_wall_direction",
        description="wall-direction randomization OFF (paddle-puck strength + direction kept on).",
        patches=[
            Patch(
                old="    enable_wall_direction_randomization: true\n",
                new="    enable_wall_direction_randomization: false\n",
            ),
        ],
    ),
    Ablation(
        name="no_action_attenuation",
        description="action force-attenuation OFF (commanded force never rescaled).",
        patches=[
            Patch(
                old="    enable_action_force_attenuation: true\n",
                new="    enable_action_force_attenuation: false\n",
            ),
        ],
    ),
    Ablation(
        name="start_100_near_top",
        description="puck_spawn_near_paddle_prob = 0.0 — episodes always start near top of table.",
        patches=[
            Patch(
                old="  puck_spawn_near_paddle_prob: 0.15\n",
                new="  puck_spawn_near_paddle_prob: 0.0\n",
            ),
        ],
    ),
    Ablation(
        name="start_100_near_paddle",
        description="puck_spawn_near_paddle_prob = 1.0 — episodes always start near paddle.",
        patches=[
            Patch(
                old="  puck_spawn_near_paddle_prob: 0.15\n",
                new="  puck_spawn_near_paddle_prob: 1.0\n",
            ),
        ],
    ),
    Ablation(
        name="no_puck_noise",
        description="additive Gaussian puck-position noise OFF.",
        patches=[
            Patch(old="    puck_noise: true\n", new="    puck_noise: false\n"),
        ],
    ),
    Ablation(
        name="no_occlusions",
        description="random puck occlusions OFF (no dropped puck observations).",
        patches=[
            Patch(
                old="    enable_random_occlusions: true\n",
                new="    enable_random_occlusions: false\n",
            ),
        ],
    ),
    Ablation(
        name="no_obs_delay",
        description="observation delay OFF (puck observed at current step, not delayed).",
        patches=[
            Patch(
                old="    enable_observation_delay: true\n",
                new="    enable_observation_delay: false\n",
            ),
        ],
    ),
    Ablation(
        name="all_sysid_no_rand",
        description=(
            "all sysid params kept at best-fit values, but ALL randomization disabled: "
            "paddle-puck strength + direction, wall direction, action force attenuation, "
            "puck noise, random occlusions, observation delay. Starting-distribution "
            "mixture (15% near-paddle / 85% near-top) is left ON because it is a "
            "deliberate curriculum, not a randomization knob."
        ),
        patches=[
            Patch(old="    puck_noise: true\n", new="    puck_noise: false\n"),
            Patch(
                old="    enable_random_occlusions: true\n",
                new="    enable_random_occlusions: false\n",
            ),
            Patch(
                old="    enable_observation_delay: true\n",
                new="    enable_observation_delay: false\n",
            ),
            Patch(
                old="    enable_action_force_attenuation: true\n",
                new="    enable_action_force_attenuation: false\n",
            ),
            Patch(
                old="    enable_paddle_puck_strength_randomization: true\n",
                new="    enable_paddle_puck_strength_randomization: false\n",
            ),
            Patch(
                old="    enable_paddle_puck_direction_randomization: true\n",
                new="    enable_paddle_puck_direction_randomization: false\n",
            ),
            Patch(
                old="    enable_wall_direction_randomization: true\n",
                new="    enable_wall_direction_randomization: false\n",
            ),
        ],
    ),
]


def apply_ablation(base_text: str, ablation: Ablation) -> str:
    text = base_text
    for patch in ablation.patches:
        count = text.count(patch.old)
        if count != 1:
            raise AssertionError(
                f"[{ablation.name}] expected exactly 1 match for old string, got {count}:\n"
                f"  {patch.old.strip()!r}"
            )
        text = text.replace(patch.old, patch.new, 1)
    diff_block = "\n".join(
        f"#   - {p.old.strip()}  ->  {p.new.strip()}" for p in ablation.patches
    )
    header = HEADER_TEMPLATE.format(description=ablation.description, diff_block=diff_block)
    # Strip the original "# Derived from ..." header (first 3 comment lines + blank)
    body_lines = text.splitlines(keepends=True)
    # Find first non-comment/blank line
    body_start = 0
    for i, line in enumerate(body_lines):
        if line.startswith("#") or line.strip() == "":
            continue
        body_start = i
        break
    body = "".join(body_lines[body_start:])
    return header + "\n" + body


def main() -> None:
    base_text = BASE.read_text()
    for ablation in ABLATIONS:
        out_path = OUT_DIR / f"sim_{ablation.name}.yaml"
        new_text = apply_ablation(base_text, ablation)
        out_path.write_text(new_text)
        print(f"wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
