"""
Behavior cloning warm-start for AMP PPO training.

This script trains the same Agent architecture used in amp_training.py
using demonstration windows generated by prepare_position_dataset_split.py.
It saves model.pth that can be loaded by amp_training.py --model_path.
"""

import os
import random
import time
from dataclasses import dataclass
from datetime import datetime
from types import SimpleNamespace

import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset, Subset
from torch.utils.tensorboard import SummaryWriter
import tyro
import yaml

from airhockey import AirHockeyEnv
from scripts.smooth_policy.agent import Agent
from scripts.smooth_policy.evaluate import evaluate_agent


def augment_policy_observation(observation, last_action, use_last_action):
    if not use_last_action:
        return observation
    return torch.cat([observation, last_action], dim=-1)


def _build_history_block_from_sequence(sequence_xy, current_idx, aux_fill):
    """Build [5,3] history block from [5,2] sequence by left-padding available prefix."""
    prefix = sequence_xy[: current_idx + 1]
    pad = 5 - prefix.shape[0]
    if pad > 0:
        prefix = torch.cat([prefix[0:1].repeat(pad, 1), prefix], dim=0)
    aux = torch.full((5, 1), float(aux_fill), dtype=sequence_xy.dtype)
    return torch.cat([prefix, aux], dim=-1)


class BCTransitionDataset(Dataset):
    """Converts [N,5,2] + [N,4,2] windows into transition-level BC samples."""

    def __init__(
        self,
        position_sequences,
        action_sequences,
        use_last_action_in_policy_state,
        puck_sequences=None,
        missing_puck_fill=0.0,
        precompute_transitions=True,
    ):
        super().__init__()
        if position_sequences.dim() != 3 or position_sequences.shape[1:] != (5, 2):
            raise ValueError(f"position_sequences must have shape [N,5,2], got {tuple(position_sequences.shape)}")
        if action_sequences.dim() != 3 or action_sequences.shape[1:] != (4, 2):
            raise ValueError(f"action_sequences must have shape [N,4,2], got {tuple(action_sequences.shape)}")
        if position_sequences.shape[0] != action_sequences.shape[0]:
            raise ValueError("position_sequences and action_sequences must have matching N.")
        if puck_sequences is not None:
            if puck_sequences.dim() != 3 or puck_sequences.shape[1:] != (5, 2):
                raise ValueError(f"puck_sequences must have shape [N,5,2], got {tuple(puck_sequences.shape)}")
            if puck_sequences.shape[0] != position_sequences.shape[0]:
                raise ValueError("position_sequences and puck_sequences must have matching N.")

        self.precompute_transitions = bool(precompute_transitions)
        self.use_last_action = bool(use_last_action_in_policy_state)
        self.missing_puck_fill = float(missing_puck_fill)
        self.num_windows = int(position_sequences.shape[0])

        self.position_sequences = None
        self.action_sequences = None
        self.puck_sequences = None
        self.observations = None
        self.expert_actions = None

        if self.precompute_transitions:
            self.observations, self.expert_actions = self._build_all_transition_samples(
                position_sequences=position_sequences,
                action_sequences=action_sequences,
                puck_sequences=puck_sequences,
            )
        else:
            self.position_sequences = position_sequences
            self.action_sequences = action_sequences
            self.puck_sequences = puck_sequences

    def __len__(self):
        if self.precompute_transitions:
            return int(self.observations.shape[0])
        return self.num_windows * 4

    def _build_all_transition_samples(self, position_sequences, action_sequences, puck_sequences):
        """Vectorized transition conversion done once to reduce per-step CPU overhead."""
        num_windows = int(position_sequences.shape[0])
        obs_by_t = []
        action_by_t = []

        if puck_sequences is None:
            missing_puck_hist = torch.full(
                (num_windows, 5, 3),
                self.missing_puck_fill,
                dtype=position_sequences.dtype,
            )
        else:
            missing_puck_hist = None

        for transition_idx in range(4):
            pad = 5 - (transition_idx + 1)

            paddle_prefix = position_sequences[:, : transition_idx + 1, :]
            if pad > 0:
                paddle_prefix = torch.cat(
                    [position_sequences[:, 0:1, :].expand(-1, pad, -1), paddle_prefix],
                    dim=1,
                )
            paddle_aux = torch.zeros((num_windows, 5, 1), dtype=position_sequences.dtype)
            paddle_hist = torch.cat([paddle_prefix, paddle_aux], dim=-1)

            if puck_sequences is not None:
                puck_prefix = puck_sequences[:, : transition_idx + 1, :]
                if pad > 0:
                    puck_prefix = torch.cat(
                        [puck_sequences[:, 0:1, :].expand(-1, pad, -1), puck_prefix],
                        dim=1,
                    )
                puck_aux = torch.zeros((num_windows, 5, 1), dtype=puck_sequences.dtype)
                puck_hist = torch.cat([puck_prefix, puck_aux], dim=-1)
            else:
                puck_hist = missing_puck_hist

            obs_t = torch.cat([paddle_hist.flatten(1), puck_hist.flatten(1)], dim=1)
            if self.use_last_action:
                if transition_idx == 0:
                    prev_action = torch.zeros_like(action_sequences[:, 0, :])
                else:
                    prev_action = action_sequences[:, transition_idx - 1, :]
                obs_t = augment_policy_observation(obs_t, prev_action, True)

            obs_by_t.append(obs_t)
            action_by_t.append(action_sequences[:, transition_idx, :])

        observations = torch.stack(obs_by_t, dim=1).reshape(num_windows * 4, -1).contiguous()
        expert_actions = torch.stack(action_by_t, dim=1).reshape(num_windows * 4, -1).contiguous()
        return observations, expert_actions

    def __getitem__(self, index):
        if self.precompute_transitions:
            return self.observations[index], self.expert_actions[index]

        window_idx = index // 4
        transition_idx = index % 4

        position_window = self.position_sequences[window_idx]
        action_window = self.action_sequences[window_idx]

        paddle_hist = _build_history_block_from_sequence(position_window, transition_idx, aux_fill=0.0)
        if self.puck_sequences is not None:
            puck_hist = _build_history_block_from_sequence(
                self.puck_sequences[window_idx],
                transition_idx,
                aux_fill=0.0,
            )
        else:
            puck_hist = torch.full(
                (5, 3),
                self.missing_puck_fill,
                dtype=position_window.dtype,
            )
        obs = torch.cat([paddle_hist.flatten(), puck_hist.flatten()], dim=0)

        expert_action = action_window[transition_idx]
        if self.use_last_action:
            prev_action = torch.zeros_like(expert_action) if transition_idx == 0 else action_window[transition_idx - 1]
            obs = augment_policy_observation(obs.unsqueeze(0), prev_action.unsqueeze(0), True).squeeze(0)

        return obs, expert_action


@dataclass
class Args:
    config: str = "scripts/smooth_policy/amp_history/configs/default_config.yaml"
    args_file: str | None = None
    demo_data_path: str = "scripts/smooth_policy/amp_history/amp_training/amp_data/amp_position_dataset_split.pt"
    log_parent_dir: str | None = None
    run_name: str = "bc_warmstart"

    seed: int = 0
    device: str = "cuda:0"
    num_envs_for_space: int = 1
    epochs: int = 40
    batch_size: int = 1024
    learning_rate: float = 1e-4
    weight_decay: float = 1e-6
    max_grad_norm: float = 0.5
    val_fraction: float = 0.05
    num_workers: int = -1
    max_auto_num_workers: int = 8
    min_train_steps_for_logging: int = 2
    early_stopping_enabled: bool = True
    early_stopping_patience: int = 8
    early_stopping_min_delta: float = 1e-4
    save_best_model: bool = True
    eval_gif_on_validation: bool = True
    eval_gif_every_epochs: int = 20
    eval_gif_n_eps: int = 4
    eval_gif_n_gifs: int = 1

    # Keep these aligned with amp_training.py for compatibility.
    use_last_action_in_policy_state: bool = False
    action_scale: float = 1.0
    agent_hidden_layer_size: int = 128
    agent_num_hidden_layers: int = 2
    # Deprecated alias kept for backward compatibility with older args files.
    agent_hidden_size: int | None = None

    # Exploration-preserving controls.
    freeze_actor_logstd: bool = True
    logstd_l2_to_init: float = 0.0
    reset_actor_logstd_after_bc: bool = True
    target_actor_logstd: float = 0.0

    # Dataset behavior.
    require_puck_sequences: bool = False
    missing_puck_fill: float = 0.0
    precompute_transition_dataset: bool = True
    dataset_load_mmap: bool = True
    warn_on_unused_long_sequences: bool = True

    # Optional initialization from existing policy.
    init_model_path: str | None = None


def make_env(air_hockey_config):
    def _thunk():
        local_cfg = dict(air_hockey_config)
        local_cfg["seed"] = random.randint(0, int(1e8))
        return AirHockeyEnv(local_cfg)

    return _thunk


def split_dataset(dataset, val_fraction, seed):
    if val_fraction <= 0.0:
        return dataset, None
    total = len(dataset)
    val_size = max(1, int(total * val_fraction))
    if val_size >= total:
        val_size = total - 1
    g = torch.Generator().manual_seed(seed)
    perm = torch.randperm(total, generator=g)
    val_idx = perm[:val_size].tolist()
    train_idx = perm[val_size:].tolist()
    return Subset(dataset, train_idx), Subset(dataset, val_idx)


def resolve_num_workers(num_workers, max_auto_num_workers):
    if num_workers >= 0:
        return num_workers
    cpu_count = os.cpu_count() or 1
    return max(1, min(int(max_auto_num_workers), cpu_count // 2))


def load_demo_dataset(demo_data_path, enable_mmap):
    load_kwargs = {"map_location": "cpu"}
    if enable_mmap:
        load_kwargs["mmap"] = True
    try:
        return torch.load(demo_data_path, **load_kwargs)
    except TypeError:
        if enable_mmap:
            print("[BC] torch.load does not support mmap in this PyTorch build; falling back to regular load.")
        return torch.load(demo_data_path, map_location="cpu")


def evaluate_bc(agent, data_loader, device):
    agent.eval()
    total_nll = 0.0
    total_mse = 0.0
    total_items = 0
    with torch.no_grad():
        for obs_batch, action_batch in data_loader:
            obs_batch = obs_batch.to(device)
            action_batch = action_batch.to(device)
            _, log_prob, mean_action, _ = agent.get_action_and_value(obs_batch, action=action_batch)
            batch_size = obs_batch.shape[0]
            total_nll += float((-log_prob.mean()).item()) * batch_size
            total_mse += float(((mean_action - action_batch) ** 2).mean().item()) * batch_size
            total_items += batch_size
    if total_items == 0:
        return {"nll": 0.0, "mse": 0.0}
    return {"nll": total_nll / total_items, "mse": total_mse / total_items}


if __name__ == "__main__":
    temp_args = tyro.cli(Args)
    if temp_args.args_file is not None:
        with open(temp_args.args_file, "r") as f:
            file_args_dict = yaml.load(f, Loader=yaml.FullLoader)
        default_args = Args(**file_args_dict)
    else:
        default_args = Args()
    args = tyro.cli(Args, default=default_args)

    if not (0.0 <= args.val_fraction < 1.0):
        raise ValueError("val_fraction must be in [0, 1).")
    if args.agent_hidden_size is not None:
        args.agent_hidden_layer_size = int(args.agent_hidden_size)
    if args.agent_num_hidden_layers < 1:
        raise ValueError("agent_num_hidden_layers must be >= 1.")
    if args.num_workers < -1:
        raise ValueError("num_workers must be >= -1.")
    if args.max_auto_num_workers < 1:
        raise ValueError("max_auto_num_workers must be >= 1.")

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    with open(args.config, "r") as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    obs_type = config["air_hockey"].get("obs_type", "history")
    if obs_type != "history":
        raise ValueError(f"BC script currently expects obs_type='history', got '{obs_type}'.")

    envs = gym.vector.AsyncVectorEnv([make_env(config["air_hockey"]) for _ in range(args.num_envs_for_space)])

    action_scale = 1.0 if config["air_hockey"].get("use_pid", False) else float(args.action_scale)
    base_obs_dim = int(np.prod(envs.single_observation_space.shape))
    action_dim = int(np.prod(envs.single_action_space.shape))
    policy_obs_dim = base_obs_dim + (action_dim if args.use_last_action_in_policy_state else 0)
    policy_env_view = SimpleNamespace(
        single_observation_space=gym.spaces.Box(
            low=-np.inf, high=np.inf, shape=(policy_obs_dim,), dtype=np.float32
        ),
        single_action_space=envs.single_action_space,
    )
    envs.close()

    if base_obs_dim != 30:
        raise ValueError(
            f"Expected base history observation dim 30 for BC window conversion, got {base_obs_dim}."
        )

    agent = Agent(
        policy_env_view,
        action_scale=action_scale,
        action_bias=0.0,
        hidden_layer_size=args.agent_hidden_layer_size,
        num_hidden_layers=args.agent_num_hidden_layers,
    ).to(args.device)
    logstd_init = agent.actor_logstd.detach().clone()

    if args.init_model_path is not None:
        if not os.path.exists(args.init_model_path):
            raise FileNotFoundError(f"init_model_path not found: {args.init_model_path}")
        agent.load_state_dict(torch.load(args.init_model_path, map_location=args.device))

    if args.freeze_actor_logstd:
        optim_params = [p for n, p in agent.named_parameters() if n != "actor_logstd"]
    else:
        optim_params = list(agent.parameters())
    optimizer = torch.optim.Adam(
        optim_params,
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
        eps=1e-6,
    )

    if not os.path.exists(args.demo_data_path):
        raise FileNotFoundError(f"Demo dataset not found: {args.demo_data_path}")
    data = load_demo_dataset(args.demo_data_path, enable_mmap=args.dataset_load_mmap)
    if "position_sequences" not in data or "action_sequences" not in data:
        raise ValueError("Dataset must contain 'position_sequences' and 'action_sequences'.")
    if args.require_puck_sequences and "puck_sequences" not in data:
        raise ValueError("require_puck_sequences=True but dataset does not contain 'puck_sequences'.")
    if args.warn_on_unused_long_sequences and (
        "position_sequences_30" in data or "puck_sequences_30" in data
    ):
        print(
            "[BC] Demo dataset includes long-sequence keys that BC does not use. "
            "For lower load overhead, rebuild dataset with --disable-long-sequences."
        )

    position_sequences = data["position_sequences"].float().contiguous()
    action_sequences = data["action_sequences"].float().contiguous()
    puck_sequences = data.get("puck_sequences", None)
    puck_sequences = puck_sequences.float().contiguous() if puck_sequences is not None else None
    del data

    dataset = BCTransitionDataset(
        position_sequences=position_sequences,
        action_sequences=action_sequences,
        puck_sequences=puck_sequences,
        use_last_action_in_policy_state=args.use_last_action_in_policy_state,
        missing_puck_fill=args.missing_puck_fill,
        precompute_transitions=args.precompute_transition_dataset,
    )
    del position_sequences, action_sequences, puck_sequences

    resolved_num_workers = resolve_num_workers(args.num_workers, args.max_auto_num_workers)
    pin_memory = bool(torch.cuda.is_available() and args.device.startswith("cuda"))
    print(
        f"[BC] DataLoader setup: num_workers={resolved_num_workers}, "
        f"pin_memory={pin_memory}, precompute_transition_dataset={args.precompute_transition_dataset}"
    )
    train_dataset, val_dataset = split_dataset(dataset, args.val_fraction, args.seed)
    loader_common_kwargs = {
        "batch_size": args.batch_size,
        "num_workers": resolved_num_workers,
        "pin_memory": pin_memory,
    }
    if resolved_num_workers > 0:
        loader_common_kwargs["persistent_workers"] = True
        loader_common_kwargs["prefetch_factor"] = 2
    train_loader = DataLoader(
        train_dataset,
        shuffle=True,
        **loader_common_kwargs,
    )
    val_loader = (
        DataLoader(
            val_dataset,
            shuffle=False,
            **loader_common_kwargs,
        )
        if val_dataset is not None
        else None
    )

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    task_name = config["air_hockey"].get("task", "task")
    log_parent_dir = args.log_parent_dir
    if log_parent_dir is None:
        log_parent_dir = f"runs/bc_pretrain/{task_name}/{args.run_name}_{timestamp}"
    if os.path.exists(log_parent_dir):
        base_dir = log_parent_dir
        idx = 1
        while os.path.exists(log_parent_dir):
            log_parent_dir = f"{base_dir}r{idx}"
            idx += 1
    os.makedirs(log_parent_dir, exist_ok=True)

    with open(f"{log_parent_dir}/config.yaml", "w") as f:
        yaml.dump(config, f)
    with open(f"{log_parent_dir}/args.yaml", "w") as f:
        yaml.dump(vars(args), f)

    writer = SummaryWriter(log_parent_dir)
    writer.add_text(
        "hyperparameters",
        "|param|value|\n|-|-|\n%s" % ("\n".join([f"|{k}|{v}|" for k, v in vars(args).items()])),
    )

    start_time = time.time()
    global_step = 0
    best_model_path = os.path.join(log_parent_dir, "model_best.pth")
    best_metric = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    stopping_metric_name = "val_nll" if val_loader is not None else "train_nll"

    for epoch in range(1, args.epochs + 1):
        agent.train()
        epoch_nll_sum = 0.0
        epoch_mse_sum = 0.0
        epoch_items = 0

        for obs_batch, action_batch in train_loader:
            obs_batch = obs_batch.to(args.device, non_blocking=True)
            action_batch = action_batch.to(args.device, non_blocking=True)

            _, log_prob, mean_action, _ = agent.get_action_and_value(obs_batch, action=action_batch)
            nll_loss = -log_prob.mean()
            mse_loss = ((mean_action - action_batch) ** 2).mean()
            loss = nll_loss

            if args.logstd_l2_to_init > 0.0:
                reg = ((agent.actor_logstd - logstd_init.to(args.device)) ** 2).mean()
                loss = loss + args.logstd_l2_to_init * reg

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(agent.parameters(), args.max_grad_norm)
            optimizer.step()

            batch_size = obs_batch.shape[0]
            epoch_nll_sum += float(nll_loss.item()) * batch_size
            epoch_mse_sum += float(mse_loss.item()) * batch_size
            epoch_items += batch_size
            global_step += 1

        train_nll = epoch_nll_sum / max(epoch_items, 1)
        train_mse = epoch_mse_sum / max(epoch_items, 1)
        val_metrics = evaluate_bc(agent, val_loader, args.device) if val_loader is not None else None
        stopping_metric = val_metrics["nll"] if val_metrics is not None else train_nll

        with torch.no_grad():
            action_std = torch.exp(agent.actor_logstd).mean().item()
            action_std_min = torch.exp(agent.actor_logstd).min().item()
            action_std_max = torch.exp(agent.actor_logstd).max().item()

        writer.add_scalar("bc/train_nll", train_nll, epoch)
        writer.add_scalar("bc/train_mse", train_mse, epoch)
        writer.add_scalar("bc/action_std_mean", action_std, epoch)
        writer.add_scalar("bc/action_std_min", action_std_min, epoch)
        writer.add_scalar("bc/action_std_max", action_std_max, epoch)
        if val_metrics is not None:
            writer.add_scalar("bc/val_nll", val_metrics["nll"], epoch)
            writer.add_scalar("bc/val_mse", val_metrics["mse"], epoch)
            if (
                args.eval_gif_on_validation
                and args.eval_gif_every_epochs > 0
                and epoch % args.eval_gif_every_epochs == 0
            ):
                checkpoint_dir = os.path.join(log_parent_dir, f"checkpoint_{epoch}")
                os.makedirs(checkpoint_dir, exist_ok=True)
                checkpoint_model_path = os.path.join(checkpoint_dir, "model.pth")
                torch.save(agent.state_dict(), checkpoint_model_path)
                evaluate_agent(
                    checkpoint_model_path,
                    checkpoint_dir,
                    config["air_hockey"],
                    n_eps=args.eval_gif_n_eps,
                    n_gifs=args.eval_gif_n_gifs,
                    action_scale=action_scale,
                    agent_hidden_layer_size=args.agent_hidden_layer_size,
                    agent_num_hidden_layers=args.agent_num_hidden_layers,
                    use_last_action_in_policy_state=args.use_last_action_in_policy_state,
                )

        # Save best checkpoint based on validation NLL when available, otherwise train NLL.
        metric_improved = (best_metric - stopping_metric) > float(args.early_stopping_min_delta)
        if metric_improved:
            best_metric = float(stopping_metric)
            best_epoch = int(epoch)
            epochs_without_improvement = 0
            if args.save_best_model:
                torch.save(agent.state_dict(), best_model_path)
        else:
            epochs_without_improvement += 1

        if epoch % max(1, args.min_train_steps_for_logging) == 0 or epoch == 1 or epoch == args.epochs:
            sps = int(global_step / max(1e-6, time.time() - start_time))
            if val_metrics is None:
                print(
                    f"[BC] epoch={epoch}/{args.epochs} train_nll={train_nll:.6f} "
                    f"train_mse={train_mse:.6f} std_mean={action_std:.4f} "
                    f"best_{stopping_metric_name}={best_metric:.6f} best_epoch={best_epoch} sps={sps}"
                )
            else:
                print(
                    f"[BC] epoch={epoch}/{args.epochs} train_nll={train_nll:.6f} "
                    f"val_nll={val_metrics['nll']:.6f} train_mse={train_mse:.6f} "
                    f"val_mse={val_metrics['mse']:.6f} std_mean={action_std:.4f} "
                    f"best_{stopping_metric_name}={best_metric:.6f} best_epoch={best_epoch} sps={sps}"
                )

        if args.early_stopping_enabled and epochs_without_improvement >= int(args.early_stopping_patience):
            print(
                f"[BC] Early stopping at epoch {epoch}: no {stopping_metric_name} improvement "
                f"for {epochs_without_improvement} epochs "
                f"(min_delta={args.early_stopping_min_delta})."
            )
            break

    if args.reset_actor_logstd_after_bc:
        with torch.no_grad():
            agent.actor_logstd.fill_(float(args.target_actor_logstd))

    model_path = os.path.join(log_parent_dir, "model.pth")
    torch.save(agent.state_dict(), model_path)
    writer.close()

    print("\n" + "=" * 80)
    print("Behavior cloning pretraining complete.")
    print(f"Saved BC warm-start model to: {model_path}")
    if args.save_best_model and os.path.exists(best_model_path):
        print(
            f"Saved best BC model to: {best_model_path} "
            f"(best_{stopping_metric_name}={best_metric:.6f} at epoch {best_epoch})"
        )
    print("Use with RL:")
    print(
        "  python scripts/smooth_policy/amp_history/amp_training/amp_training.py "
        f"--model_path {model_path}"
    )
    print("Exploration-friendly RL handoff tips:")
    print("  - keep ent_coef non-zero (e.g. 0.005-0.02)")
    print("  - use conservative learning_rate at startup")
    print("  - avoid overly large discriminator reward weights in first iterations")
    print("=" * 80)
