num_envs: 2
num_steps: 64
learning_rate: 0.0001
num_iterations: 2
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
minibatch_size: 32
update_epochs: 4
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
norm_adv: true
config: scripts/smooth_policy/configs/puck_touch/default_config.yaml
args_file: null
model_path: null
log_parent_dir: null
run_name: pid_test
seed: 0
device: cpu

