air_hockey:
  base_reward_scaling: 1
  diagonal_motion_rew: 0.0
  direction_change_rew: 0.0
  goal_max_x_velocity: 1
  goal_max_y_velocity: 5
  goal_min_y_velocity: 1
  horizontal_vel_rew: 0.0
  max_timesteps: 250
  n_training_steps: 1000000
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  obs_type: history
  puck_linear_top_spawn_center_cutoff_x: 0.2
  puck_linear_top_spawn_goal_cutoff_x: null
  puck_linear_top_spawn_speed_max: 0.5
  puck_linear_top_spawn_speed_min: 0.0
  puck_near_paddle_horizontal_std_m: 0.015
  puck_near_paddle_offset_max_m: 0.05
  puck_near_paddle_offset_min_m: 0.025
  puck_near_paddle_speed_max_m_s: 0.2
  puck_near_paddle_speed_min_m_s: 0.0
  puck_spawn_near_paddle_prob: 0.15
  return_goal_obs: false
  seed: 77406190
  simulator: box2d
  simulator_params:
    absorb_target: false
    action_force_attenuation_max: 0.75
    action_force_attenuation_min: 0.25
    action_force_attenuation_prob: 0.3
    block_density: 1000
    block_width: 0.0254
    delay_relative_range: 0.25
    delay_seconds: 0.025
    enable_action_delay: false
    enable_action_force_attenuation: true
    enable_observation_delay: true
    enable_paddle_puck_direction_randomization: true
    enable_paddle_puck_strength_randomization: true
    enable_puck_delay_interpolation: true
    enable_random_occlusions: true
    enable_wall_direction_randomization: true
    end_wall_restitution: 0.7
    force_scaling: 0.99
    gravity: -0.661
    hist_len: 5
    length: 1.9304
    max_force_timestep: 10000
    paddle_damping: 17
    paddle_density: 3000
    paddle_puck_direction_cone_deg: 10.0
    paddle_puck_strength_range:
    - 0.5
    - 1.0
    paddle_radius: 0.0508
    paddle_restitution: 0.8
    pid_kd: 50
    pid_ki: 0.0
    pid_kp: 9000
    puck_damping: 0.178
    puck_density: 3000
    puck_noise: true
    puck_noise_std: 0.01
    puck_radius: 0.03175
    puck_restitution: 0.87316
    random_occlusion_bad_region_box_x:
    - -0.4
    - -0.35
    random_occlusion_bad_region_box_y:
    - -0.3
    - 0.0
    random_occlusion_bad_region_right_x:
    - 0.35
    - 0.8
    random_occlusion_length_weights:
    - 75
    - 39
    - 18
    - 9
    - 4
    - 2
    - 1
    random_occlusion_near_paddle_boost: true
    random_occlusion_near_paddle_distance_m: 0.05
    random_occlusion_near_paddle_rate_multiplier: 3.0
    random_occlusion_other_region_rate: 0.025
    random_occlusion_target_rate: 0.025
    randomize_delay: true
    render_size: 360
    seed: 0
    side_wall_restitution: 0.925
    use_pid: true
    wall_direction_cone_deg: 10.0
    width: 0.8636
  stand_still_rew: 0.0
  task: puck_juggle_upper_half_reward
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: false
  terminate_on_puck_hit_bottom: true
  terminate_on_puck_hit_paddle: false
  terminate_on_puck_pass_paddle: true
  terminate_on_puck_stop: false
  truncate_rew: 0
  use_reward_shaping: true
  use_smooth_penalty: false
  wall_bumping_rew: 0
