action_coef: 0.0
anneal_lr: false
args_file: runs/base_args.yaml
batch_size: 4096
caps_coef_consecutive: 0.0
caps_coef_nearby: 0.0
clip_coef: 0.2
clip_vloss: false
config: scripts/smooth_policy/configs/puck_juggle/velocity.yaml
device: cuda:0
dynamic_freeze_policy: true
dynamic_reward_scaling: true
ent_coef: 0.02
finetune: false
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0001
log_parent_dir: runs/freeze_policy/compare_normalize_advantage/dynamic_reward_scaling-True_dynamic_freeze_policy-True_vf_coef-0.1/seed_0
max_grad_norm: 0.5
minibatch_size: 64
model_path: null
norm_adv: true
num_envs: 1
num_iterations: 500
num_steps: 4096
reward_normalization: false
reward_scaling: true
run_name: sweep_dynamic_reward_scaling-True_dynamic_freeze_policy-True_vf_coef-0.1_seed_0
seed: 0
target_kl: null
update_epochs: 10
vf_coef: 0.5
