air_hockey:
  base_goal_radius: 0.1
  base_goal_speed_radius: 0.5
  goal_position_margin: 0.1
  goal_radius_type: fixed
  goal_shot_max_angle_deg: 45.0
  goal_shot_min_upward_speed: 0.3
  goal_shot_speed_range:
  - 1.0
  - 3.0
  goal_velocity_sampling: shot
  max_timesteps: 250
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  obs_type: history
  return_goal_obs: true
  seed: 0
  simulator: box2d
  simulator_params:
    absorb_target: false
    block_density: 1000
    block_width: 0.0254
    delay_seconds: 0.025
    enable_action_delay: false
    enable_observation_delay: true
    enable_puck_delay_interpolation: true
    enable_random_occlusions: true
    end_wall_restitution: 0.7
    force_scaling: 0.99
    gravity: -0.661
    hist_len: 2
    length: 1.9304
    max_force_timestep: 10000
    paddle_damping: 17
    paddle_density: 3000
    paddle_radius: 0.0508
    paddle_restitution: 1.0
    pid_kd: 50
    pid_ki: 0.0
    pid_kp: 9000
    puck_damping: 0.178
    puck_density: 3000
    puck_noise: true
    puck_noise_std: 0.01
    puck_radius: 0.03175
    puck_restitution: 1.09145
    random_occlusion_rate: 0.05
    render_size: 360
    seed: 0
    side_wall_restitution: 0.99
    width: 0.8636
  task: puck_goal_position_speed_sparse
  terminate_on_enemy_goal: true
  terminate_on_goal_reached: true
  terminate_on_out_of_bounds: false
  terminate_on_puck_hit_bottom: true
  terminate_on_puck_hit_paddle: false
  terminate_on_puck_pass_paddle: true
  terminate_on_puck_stop: false
