#!/usr/bin/env python3
"""
Generate TD3 args YAMLs for the zero-shot sim2real ablation sweep.

Each TD3 args YAML is identical to td3_hist2_motion0_v2.yaml (the recipe
that trained latest_model/hist2_motion0_v2/) with these overrides:
  - total_timesteps: 500000  (down from 1M)
  - config:           points to the per-ablation sim YAML
  - log_parent_dir:   runs/td3/zeroshot_ablations/<name>/seed0
  - run_name:         td3_zeroshot_<name>
  - device:           cuda:0 or cuda:1 (assigned to balance the queue)

Two GPUs free (0 and 1). 12 runs total. Round-robin assignment so each GPU
runs ~6 sequential 500k-step jobs.

Run from repo root:
    .venv/bin/python scripts/smooth_policy/amp_history/configs/td3/zeroshot_ablations/_generate.py
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[6]
BASE = REPO_ROOT / "scripts/smooth_policy/amp_history/configs/td3/td3_hist2_motion0_v2.yaml"
OUT_DIR = Path(__file__).resolve().parent
SIM_DIR = REPO_ROOT / "scripts/smooth_policy/amp_history/configs/new_juggle/zeroshot_ablations"
CANONICAL_SIM = REPO_ROOT / "scripts/smooth_policy/amp_history/configs/new_juggle/sysid_best_params_hist2.yaml"


@dataclass
class Run:
    name: str  # used as filename: td3_zeroshot_<name>.yaml and run_name suffix
    sim_path: Path  # which sim YAML to point `config:` at
    description: str
    device: str  # "cuda:0" or "cuda:1"


# Round-robin: cuda:0 gets even index, cuda:1 gets odd
ABLATIONS = [
    ("baseline", CANONICAL_SIM, "Baseline — canonical hist2 sysid sim, no knobs flipped, 500k steps."),
    ("sysid_off", SIM_DIR / "sim_sysid_off.yaml", "Sysid params reverted to legacy off-the-shelf values."),
    ("no_paddle_puck_strength", SIM_DIR / "sim_no_paddle_puck_strength.yaml", "Paddle-puck strength randomization OFF."),
    ("no_paddle_puck_direction", SIM_DIR / "sim_no_paddle_puck_direction.yaml", "Paddle-puck direction randomization OFF."),
    ("no_wall_direction", SIM_DIR / "sim_no_wall_direction.yaml", "Wall-direction randomization OFF."),
    ("no_action_attenuation", SIM_DIR / "sim_no_action_attenuation.yaml", "Action force-attenuation OFF."),
    ("start_100_near_top", SIM_DIR / "sim_start_100_near_top.yaml", "100% near-top starts (puck_spawn_near_paddle_prob=0)."),
    ("start_100_near_paddle", SIM_DIR / "sim_start_100_near_paddle.yaml", "100% near-paddle starts (puck_spawn_near_paddle_prob=1)."),
    ("no_puck_noise", SIM_DIR / "sim_no_puck_noise.yaml", "Additive Gaussian puck noise OFF."),
    ("no_occlusions", SIM_DIR / "sim_no_occlusions.yaml", "Random puck occlusions OFF."),
    ("no_obs_delay", SIM_DIR / "sim_no_obs_delay.yaml", "Observation delay OFF."),
    ("all_sysid_no_rand", SIM_DIR / "sim_all_sysid_no_rand.yaml", "Sysid kept; ALL collision/action/observation randomization OFF."),
]

RUNS: list[Run] = [
    Run(
        name=name,
        sim_path=sim_path,
        description=description,
        device=f"cuda:{i % 2}",
    )
    for i, (name, sim_path, description) in enumerate(ABLATIONS)
]


def render(base_text: str, run: Run) -> str:
    rel_sim = run.sim_path.relative_to(REPO_ROOT)
    rel_log_parent = f"runs/td3/zeroshot_ablations/{run.name}/seed0"
    run_name = f"td3_zeroshot_{run.name}"

    text = base_text

    # Patches — each must match exactly once.
    patches = [
        ("total_timesteps: 1000000\n", "total_timesteps: 500000\n"),
        (
            'config: "scripts/smooth_policy/amp_history/configs/new_juggle/sysid_best_params_hist2.yaml"\n',
            f'config: "{rel_sim}"\n',
        ),
        (
            'log_parent_dir: "runs/td3/hist_motion_collision/hist2_motion0_v2/seed0"\n',
            f'log_parent_dir: "{rel_log_parent}"\n',
        ),
        (
            'run_name: "td3_hist2_motion0_v2"\n',
            f'run_name: "{run_name}"\n',
        ),
        ('device: "cuda:0"\n', f'device: "{run.device}"\n'),
    ]
    for old, new in patches:
        if text.count(old) != 1:
            raise AssertionError(
                f"[{run.name}] expected exactly 1 match for {old.strip()!r} in base td3 args"
            )
        text = text.replace(old, new, 1)

    header = (
        f"# Zero-shot sim2real ablation: {run.description}\n"
        f"# Auto-generated by _generate.py from td3_hist2_motion0_v2.yaml.\n"
        f"# Diff vs base recipe: 500k steps (was 1M); config points at {rel_sim};\n"
        f"# log/run dir scoped to runs/td3/zeroshot_ablations/{run.name}/; device {run.device}.\n"
        f"#\n"
    )

    # Strip the original 14-line comment header from td3_hist2_motion0_v2.yaml
    body_lines = text.splitlines(keepends=True)
    body_start = 0
    for i, line in enumerate(body_lines):
        if line.startswith("#") or line.strip() == "":
            continue
        body_start = i
        break
    return header + "\n" + "".join(body_lines[body_start:])


def main() -> None:
    base_text = BASE.read_text()
    for run in RUNS:
        out_path = OUT_DIR / f"td3_zeroshot_{run.name}.yaml"
        out_path.write_text(render(base_text, run))
        print(f"wrote {out_path.relative_to(REPO_ROOT)}  [{run.device}]")

    # Also emit a queue file per GPU for the launcher script.
    for gpu in (0, 1):
        names = [r.name for r in RUNS if r.device == f"cuda:{gpu}"]
        queue_path = OUT_DIR / f"_queue_gpu{gpu}.txt"
        queue_path.write_text("\n".join(names) + "\n")
        print(f"wrote {queue_path.relative_to(REPO_ROOT)}  ({len(names)} runs)")


if __name__ == "__main__":
    main()
