air_hockey:
  max_timesteps: 300
  num_blocks: 0
  num_obstacles: 0
  num_paddles: 1
  num_pucks: 1
  num_targets: 0
  obs_type: pos # history # vel
  simulator: real
  simulator_params:
    absorb_target: false
    block_density: 500
    block_width: 0.0254
    force_scaling: 1000
    gravity: -0.5
    length: 1.9304
    max_force_timestep: 100
    paddle_damping: 3
    paddle_density: 2500
    paddle_radius: 0.0508
    puck_damping: 0.5
    puck_density: 250
    puck_hit_bottom_boundary_m: 0.2
    puck_radius: 0.03175
    render_size: 360
    wall_bounce_scale: 0.02
    width: 0.8636
    control_mode: mouse
    wait_for_space_to_start: true
    save_path: ./data/rollout/temp_saving/mouse_test
    hist_len: 4
  stand_still_rew: 0.01
  task: puck_velocity
  terminate_on_enemy_goal: true
  terminate_on_out_of_bounds: true
  terminate_on_puck_hit_bottom: true
  terminate_on_puck_hit_paddle: false
  terminate_on_puck_pass_paddle: true
  terminate_on_puck_stop: false
